
version: 2
.conan-steps: &conan-steps
  steps:
    - checkout
    - run:
        name: Update Conan package
        command: |
          chmod +x .circleci/install.sh
          .circleci/install.sh
    - run:
        name: Build recipe
        command: |
          sudo pip install --upgrade conan
          conan user
          conan create . user/channel -pr gcc7-x64.profile
        environment:
          CONAN_REFERENCE: "fcdk/1.0.0"
          CONAN_USERNAME: "user"
          CONAN_CHANNEL: "channel"
          
jobs:
  gcc-7:
      docker:
        - image: conanio/gcc7
      environment:
        - CONAN_GCC_VERSIONS: "7"
      <<: *conan-steps


workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc-7


